### ISSUE TITLE
css issue for smaller screens

### ISSUE THREAD

**Issue by C0rruptedL** [thatshawt/ratClicker#40]
@thatshawt 

![asdf1](https://user-images.githubusercontent.com/47637274/53339181-958fe080-38d3-11e9-84b6-6ba91e55f145.PNG)

**Comment by thatshawt** [comment]
fein

**Comment by Minashi** [comment]
Dammit, I know how to fix it but I'm pooping sleepy with my 2 hour 30 minute sleep

**Comment by thatshawt** [comment]
i fixed it
#42
