### ISSUE TITLE
bad logo

### ISSUE THREAD

**Issue by C0rruptedL** [thatshawt/ratClicker#41]
use the logo recommended by most dentists
![g](https://user-images.githubusercontent.com/47637274/53348460-12798500-38e9-11e9-8664-4ba0536ec21b.PNG)

**Comment by C0rruptedL** [comment]
superior logo

**Comment by thatshawt** [comment]
its too cheesy

**Comment by thatshawt** [comment]
![image](https://user-images.githubusercontent.com/5741581/53379230-c9502200-3936-11e9-83a7-33fe92623430.png)
